---
- hosts: agent
  become: true
  vars:
   ansible_become_pass: edureka
  tasks:
  - name: Install Git
    package:
     name: git
     state: present
  - name: Run update
    apt: 
     update_cache: true

  - name: Install jdk
    package:
     name: degault-jdk
     stae: present

  - name: copy chromedriver
    copy:
     src: /home/edureka/chromedriver
     dest: /home/edureka/

  - name: Install chromium browser
    package: 
     name: chromium-browser
     state: present

  - name: Install chromium driver
    package:
     name: chromium-chromedriver
     state: present

  - name: copy agent.jar file
    copy:
     src: /home/edureka/downloads/agent.jar
     dest: /home/edureka

  - name: Run update
    apt: 
     update_cache: yes

